# Generated by Django 4.0.1 on 2022-04-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetailsModel',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(help_text='Enter FullName', max_length=100)),
                ('org', models.CharField(help_text='Enter Email id', max_length=100)),
                ('price', models.IntegerField(help_text='Enter Mobile Number', null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('contact', models.BigIntegerField(help_text='Enter Mobile Number', null=True)),
                ('email', models.EmailField(help_text='Enter Mobile Number', max_length=254, null=True)),
                ('description', models.TextField(help_text='Enter Mobile Number', null=True)),
            ],
            options={
                'db_table': 'service_details',
            },
        ),
    ]
