# Generated by Django 4.0.1 on 2022-04-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_servicedetailsmodel_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetailsmodel',
            name='service_status',
            field=models.CharField(default='pending', help_text='Enter Email id', max_length=100, null=True),
        ),
    ]
