# Generated by Django 4.0.1 on 2022-04-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banquetapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetailsModel',
            new_name='BanquetDetailsModel',
        ),
        migrations.AlterModelTable(
            name='banquetdetailsmodel',
            table='banquet_details',
        ),
    ]
