# Generated by Django 4.0.1 on 2022-04-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquetapp', '0002_rename_userdetailsmodel_banquetdetailsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanquetProfileModel',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('venue_category', models.CharField(help_text='Enter FullName', max_length=100)),
                ('venue_location', models.CharField(help_text='Enter FullName', max_length=100)),
                ('name', models.CharField(help_text='Enter FullName', max_length=100)),
                ('contact', models.IntegerField()),
                ('price', models.IntegerField(help_text='Enter Mobile Number', null=True)),
                ('year_built', models.IntegerField(help_text='Enter Mobile Number', null=True)),
                ('seating_capacity', models.IntegerField(help_text='Enter Mobile Number', null=True)),
                ('bathrooms', models.IntegerField(help_text='Enter Mobile Number', null=True)),
                ('two_parking_area', models.IntegerField(help_text='Enter Mobile Number', null=True)),
                ('four_parking_area', models.IntegerField(help_text='Enter Mobile Number', null=True)),
                ('super_buildup_area', models.IntegerField(help_text='Enter Mobile Number', null=True)),
                ('carpet_area', models.IntegerField(help_text='Enter Mobile Number', null=True)),
                ('non_veg_plate', models.IntegerField(help_text='Enter Mobile Number', null=True)),
                ('total_floors', models.IntegerField(null=True)),
                ('first_image', models.ImageField(null=True, upload_to='images/')),
                ('second_imagee', models.ImageField(null=True, upload_to='images/')),
                ('third_imageee', models.ImageField(null=True, upload_to='images/')),
                ('fourth_image', models.ImageField(null=True, upload_to='images/')),
                ('dj', models.CharField(help_text='Enter FullName', max_length=100)),
                ('deco', models.CharField(help_text='Enter FullName', max_length=100)),
                ('catering', models.CharField(help_text='Enter FullName', max_length=100)),
                ('room', models.CharField(help_text='Enter FullName', max_length=100)),
                ('music', models.CharField(help_text='Enter FullName', max_length=100)),
                ('crackers', models.CharField(help_text='Enter FullName', max_length=100)),
                ('description', models.TextField(help_text='Enter FullName')),
                ('address', models.CharField(help_text='Enter FullName', max_length=100)),
            ],
            options={
                'db_table': 'banquet_profile_details',
            },
        ),
    ]
