# Generated by Django 4.0.1 on 2022-04-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquetapp', '0003_banquetprofilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetprofilemodel',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
