# Generated by Django 4.0.1 on 2022-04-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquetapp', '0004_alter_banquetprofilemodel_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanquetBookingModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('occasion', models.CharField(help_text='Enter FullName', max_length=100)),
                ('date', models.DateField(help_text='Enter FullName', max_length=100)),
                ('time', models.TimeField(help_text='Enter FullName', max_length=100)),
                ('contact', models.BigIntegerField()),
                ('price', models.IntegerField(help_text='Enter Mobile Number', null=True)),
                ('guest', models.IntegerField(help_text='Enter Mobile Number', null=True)),
                ('groom', models.CharField(help_text='Enter FullName', max_length=100)),
                ('bride', models.CharField(help_text='Enter FullName', max_length=100)),
                ('deco', models.CharField(help_text='Enter FullName', max_length=100)),
                ('serving', models.CharField(help_text='Enter FullName', max_length=100)),
                ('plate_price', models.IntegerField(help_text='Enter FullName')),
                ('user', models.CharField(help_text='Enter FullName', max_length=100)),
                ('advance', models.IntegerField(help_text='Enter Mobile Number', null=True)),
                ('services', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(help_text='Enter FullName')),
                ('address', models.CharField(help_text='Enter FullName', max_length=100)),
            ],
            options={
                'db_table': 'banquet_booking_details',
            },
        ),
    ]
