# Generated by Django 4.0.1 on 2022-04-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquetapp', '0005_banquetbookingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetprofilemodel',
            name='banquet_status',
            field=models.CharField(default='pending', help_text='Enter FullName', max_length=100),
        ),
    ]
