# Generated by Django 4.0.1 on 2022-04-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banquetapp', '0006_banquetprofilemodel_banquet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetprofilemodel',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='banquetapp.banquetdetailsmodel'),
        ),
    ]
