# Generated by Django 4.0.1 on 2022-04-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquetapp', '0007_banquetprofilemodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banquetprofilemodel',
            name='banquet_status',
        ),
        migrations.AddField(
            model_name='banquetdetailsmodel',
            name='banquet_status',
            field=models.CharField(default='pending', help_text='Enter FullName', max_length=100),
        ),
    ]
