# Generated by Django 4.0.1 on 2022-05-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquetapp', '0008_remove_banquetprofilemodel_banquet_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetprofilemodel',
            name='map',
            field=models.TextField(help_text='Enter FullName', null=True),
        ),
    ]
