# Generated by Django 4.0.1 on 2022-05-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banquetapp', '0009_banquetprofilemodel_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetbookingmodel',
            name='profile_id',
            field=models.ForeignKey(db_column='profile_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='banquetapp.banquetprofilemodel'),
        ),
    ]
