# Generated by Django 4.0.1 on 2022-04-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='Enter FullName', max_length=100)),
                ('feedback', models.CharField(help_text='Enter Password', max_length=100)),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
    ]
